name: Flashpay Assets CI
on:
  push:
    branches:
      - main
      - test

env:
  API_KEY: ${{ secrets.API_KEY }}
  API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
  NETWORK: "${{ github.ref_name }}net"
  CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}

jobs:
  update_assets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Dependencies
        run: "pip install -r requirements.txt"

      - name: Update Assets
        run: "python upload.py"

  update_last_update_ts:
    needs: ['update_assets']
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.9'
          cache: 'pip'

      - name: Run Script
        run: "python update_info_txt.py"

      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git add info.txt
          git commit -m "Update info.txt"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}